modmap:
  - name: main
    remap:
      CapsLock: leftctrl

keymap:
  - name: vim-like bindings
    application:
      not: "St"
    remap:
      C-k: up
      C-j: down
      C-h: left
      C-l: right
  - name: firefox navigation
    application:
      only: "Firefox"
    remap:
      C-k: up
      C-j: down
      C-h: left
      C-l: right
