add_newline = false

format = """
$conda\
$hostname\
$directory\
$git_branch\
$git_status\
$character
"""
right_format = """$cmd_duration"""

[conda]
symbol = ""
format = '[$symbol $environment](bold red) '


[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) - [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false

[character]
success_symbol = "[ﰲ](blue)"
error_symbol   = "[ﰲ](red)"
vicmd_symbol   = "[ﰲ](green)"

[line_break]
disabled = true

[cmd_duration]
min_time = 0 
format = "[$duration](bold yellow)"

[username]
style_user = "red bold"
style_root = "black bold"
format = '\[[$user]($style)\] '
disabled = false
show_always = true

[directory]
style = "bold blue"
format = '[$path]($style)[$read_only]($read_only_style) '
read_only = " "
# truncation_length = 3
truncate_to_repo = false 

[git_branch]
symbol = " "
style = "bold red" 

[git_status]
untracked = "?"
modified = "!"
deleted = ""
style = "bold yellow" 
staged = '[++\($count\)](green)'
